export const GET_LIMIT_ORDERS = "GET_LIMIT_ORDERS";
export const GET_STOP_ORDERS = "GET_STOP_ORDERS";
export const GET_POSITIONS = "GET_POSITIONS";
export const GET_WAITING_TRAILING_STOPS = "GET_WAITING_TRAILING_STOPS";
export const POST_TRAILING_STOP = "POST_TRAILING_STOP";

export const GET_ACCOUNTS = "GET_ACCOUNTS";
export const POST_ACCOUNT = "POST_ACCOUNT";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";

export const GET_ALERTS = "GET_ALERTS";
export const POST_ALERT = "POST_ALERT";
export const DELETE_ALERT = "DELETE_ALERT";

export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const CLEAR_CAPABILITY_CLOSE_MODAL = "CLEAR_CAPABILITY_CLOSE_MODAL";
export const GET_ERRORS = "GET_ERRORS";
