export const GET_ORDERS = "GET_ORDERS";
export const GET_STOPS = "GET_STOPS";
export const GET_POSITIONS = "GET_POSITIONS";
export const GET_ERRORS = "GET_ERRORS";
export const GET_WAITING_TRAILING_STOPS = "GET_WAITING_TRAILING_STOPS";

export const SET_CURRENT_USER = "SET_CURRENT_USER";
